# Generated by Django 6.0 on 2025-12-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField()),
                ('browser', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('short_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='urls.shorturl')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='analytics_c_timesta_a48cd6_idx')],
            },
        ),
    ]
