# Generated by Django 6.0 on 2025-12-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickevent',
            old_name='short_code',
            new_name='short_url',
        ),
    ]
